"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.openRouteInDesktopApp = exports.isChromeIOS = exports.isMobileChrome = exports.isModernSafari = exports.isSafari = exports.isMobileWebKit = exports.isMobileSafari = exports.isMobileIOS = exports.isMobile = exports.getBrowser = void 0;
const getBrowser = () => '';
exports.getBrowser = getBrowser;
const isMobile = () => false;
exports.isMobile = isMobile;
const isMobileIOS = () => false;
exports.isMobileIOS = isMobileIOS;
const isMobileSafari = () => false;
exports.isMobileSafari = isMobileSafari;
const isMobileChrome = () => false;
exports.isMobileChrome = isMobileChrome;
const isMobileWebKit = () => false;
exports.isMobileWebKit = isMobileWebKit;
const isChromeIOS = () => false;
exports.isChromeIOS = isChromeIOS;
const isSafari = () => false;
exports.isSafari = isSafari;
const isModernSafari = () => false;
exports.isModernSafari = isModernSafari;
const openRouteInDesktopApp = () => { };
exports.openRouteInDesktopApp = openRouteInDesktopApp;
