"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FOOTER_BOTTOM_MARGIN = exports.MARGIN_FROM_INPUT_ANDROID = exports.MARGIN_FROM_INPUT_IOS = void 0;
const MARGIN_FROM_INPUT_IOS = 28;
exports.MARGIN_FROM_INPUT_IOS = MARGIN_FROM_INPUT_IOS;
const MARGIN_FROM_INPUT_ANDROID = 20;
exports.MARGIN_FROM_INPUT_ANDROID = MARGIN_FROM_INPUT_ANDROID;
const FOOTER_BOTTOM_MARGIN = 20;
exports.FOOTER_BOTTOM_MARGIN = FOOTER_BOTTOM_MARGIN;
